# Generated by Django 3.0.7 on 2020-07-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainBook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='url',
        ),
    ]
