# Generated by Django 3.0.7 on 2020-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBook', '0002_remove_direction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='tagline',
            field=models.CharField(default='', max_length=100, verbose_name='Слоган'),
        ),
    ]
