# Generated by Django 3.0.7 on 2020-07-11 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=300, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Пост')),
                ('homework', models.TextField(verbose_name='Домашнее задание')),
                ('poster', models.ImageField(upload_to='backend_poster/', verbose_name='Постер')),
                ('year', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
    ]
